### ISSUE TITLE
Web端分享按钮对齐问题（播放面板位置对齐问题）

### ISSUE THREAD

**Issue by oldking139** [chobitsnerv/lite-web-studio#36]
![image](https://user-images.githubusercontent.com/45203648/156878043-05c55b92-1a6c-4635-a6c7-5ae0c80cc024.png)

**Comment by oldking139** [comment]
![image](https://user-images.githubusercontent.com/45203648/156878112-ea212933-eeaf-4513-be93-a035f32168cd.png)

**Comment by chobitsnerv** [comment]
Fixed
