### ISSUE TITLE
音频托管服务商更换

### ISSUE THREAD

**Issue by Zxilly** [chobitsnerv/lite-web-studio#49]
比起存 `sharepoint`，其实可以 `git lfs` 直接存 `GitHub` 吧，还能蹭 `jsdelivr` 的加速

**Comment by oldking139** [comment]
目前正在考虑多种方案。

**Comment by chobitsnerv** [comment]
网盘资源还在提供给其他用户便捷下载，git lfs对于无相关背景的用户可能会造成不变，需要进一步考量。
增加了切换国内网盘地址的选项，根据改善情况再做下一步评估。

**Comment by chobitsnerv** [comment]
已发布资源选择模式，欢迎提供反馈。
