### ISSUE TITLE
修复”当播放列表中，有歌曲移至当前播放歌曲的前面时，当前播放歌曲切换至前一首“的问题

### ISSUE THREAD

**Issue by oldking139** [chobitsnerv/lite-web-studio#52]
复现
https://user-images.githubusercontent.com/45203648/157142676-fb64d238-f04b-4baf-a437-27352678f8fa.mp4

https://discord.com/channels/812429711359475743/944894190318415873/950526607519535164

**Comment by chobitsnerv** [comment]
歌曲信息会被更换但是歌曲本身不会变更，已经修复并发布。
