### ISSUE TITLE
录播地址错误

### ISSUE THREAD

**Issue by xizeyoupan** [chobitsnerv/lite-web-studio#56]
![image](https://user-images.githubusercontent.com/44920131/157463609-5165579e-2068-4441-9e96-ca5fa9993758.png)
in `src\components\MainSongList.vue` and `src\components\popup\Details.vue`
```diff
<a
  v-bind:href="
    'https://www.bilibili.com/video/' +
    song.record.bv +
+   '?' +
+   (song.record.p ? 'p=' + song.record.p : '') + 
-    (song.record.p ? '?p=' + song.record.p : '') +
     (song.record_start_ms
     ? '&start_progress=' + song.record_start_ms
     : '')
  "
  target="_blank"
  rel="noreferrer noopener"
>
```

btw，what is `start_progress` param？

**Comment by chobitsnerv** [comment]
BV跳转起始定位时间，现在为全部校对故暂时没有启用。

**Comment by chobitsnerv** [comment]
fixed

**Comment by xizeyoupan** [comment]
> fixed

`src\components\popup\Details.vue`里的是等下次再修复吗
