### ISSUE TITLE
歌曲对应录播路径跳转失败？

### ISSUE THREAD

**Issue by fjkkkya** [chobitsnerv/lite-web-studio#96]
在歌曲信息的录播路径点击会跳转到B站首页，而不会跳转到对应页面，这是B站的屏蔽规则导致的？

**Comment by chobitsnerv** [comment]
新的歌曲由于没有确定要使用的B站录播链接，所以就没有提供跳转的目标，因此显示为主页。
如果对于补充相关信息感兴趣，欢迎来一起贡献数据库。
